In [1]:
! pip install stable_baselines3
!  pip install gym[box2d]
!pip install Box2D
import gym
import gym
import numpy as np 
import matplotlib.pyplot as plt
import time
from time import sleep
import random

  Using cached box2d-py-2.3.5.tar.gz (374 kB)
  Running setup.py clean for box2d-py
Failed to build box2d-py
    Running setup.py install for box2d-py: started
    Running setup.py install for box2d-py: finished with status 'error'


  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Jonathan\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Jonathan\\AppData\\Local\\Temp\\pip-install-ykwx378z\\box2d-py\\setup.py'"'"'; __file__='"'"'C:\\Users\\Jonathan\\AppData\\Local\\Temp\\pip-install-ykwx378z\\box2d-py\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Jonathan\AppData\Local\Temp\pip-wheel-i1uhjo4k'
       cwd: C:\Users\Jonathan\AppData\Local\Temp\pip-install-ykwx378z\box2d-py\
  Complete output (28 lines):
  Using setuptools (version 50.3.1.post20201107).
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\Box2D
  copying library\Box2D\Box2D.py -> build\lib.win-amd64-3.8\Box2D
  copying library\Box2D\__init__.py

In [2]:
env = gym.make("Taxi-v3").env
env.reset()
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [3]:
print("Action Space {}".format(env.action_space))
print("State Space {}".format(env.observation_space))

Action Space Discrete(6)
State Space Discrete(500)


In [4]:
# initialize variables
alpha = 0.9 #learning rate                 
discount_factor = 0.618               
epsilon = 1                  
max_epsilon = 1
min_epsilon = 0.01         
decay = 0.01

train_episodes = 2000    
test_episodes = 100          
max_steps = 100

# initialize q table
qtable = np.zeros((env.observation_space.n, env.action_space.n))
qtable

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
rewards = []
epsilons = []

for episode in range(train_episodes):
    state = env.reset()
    total_training_rewards = 0

In [6]:
for step in range(2000):
    exp_exp_tradeoff = random.uniform(0, 1) 
    if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:]) 
    else:
            action = env.action_space.sample()
    
    # determining new state after making a move 
    newstate, reward, done , info = env.step(action)
    
    # implementing the formula to the q table
    print(reward)
    qtable[state, action] = qtable[state, action]+alpha*(reward+discount_factor*np.max(qtable[newstate, :])-qtable[state, action])
    print(qtable)
    total_training_rewards += reward
    state = newstate
    
    #returning the final reward after many episodes
    if done == True :
        print ("Total reward for episode {}: {}".format(episode, total_training_rewards))
        break
   
    # updating epsilon
    epsilon = min_epsilon+(max_epsilon-min_epsilon)*np.exp(-decay*episode)
    
    #Adding the total reward and reduced epsilon values
    rewards.append(total_training_rewards)
    epsilons.append(epsilon)
print(rewards)
print ("Training score over time: " + str(sum(rewards)/train_episodes))

-10
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
-1
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
-1
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
-1
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
-1
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
-1
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
-1
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
-1
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0

 [ 0.       0.       0.       0.       0.       0.     ]]
-1
[[ 0.       0.       0.       0.       0.       0.     ]
 [ 0.       0.       0.       0.       0.       0.     ]
 [-1.49058 -0.9     -0.9     -0.9     -0.9     -9.     ]
 ...
 [ 0.       0.       0.       0.       0.       0.     ]
 [ 0.       0.       0.       0.       0.       0.     ]
 [ 0.       0.       0.       0.       0.       0.     ]]
-1
[[ 0.       0.       0.       0.       0.       0.     ]
 [ 0.       0.       0.       0.       0.       0.     ]
 [-1.49058 -1.49058 -0.9     -0.9     -0.9     -9.     ]
 ...
 [ 0.       0.       0.       0.       0.       0.     ]
 [ 0.       0.       0.       0.       0.       0.     ]
 [ 0.       0.       0.       0.       0.       0.     ]]
-1
[[ 0.         0.         0.         0.         0.         0.       ]
 [ 0.         0.         0.         0.         0.         0.       ]
 [-1.49058   -1.49058   -1.8190606 -0.9       -0.9       -9.       ]
 ...
 [ 0.         0.         

In [7]:
print(qtable)

[[ 0.         0.         0.         0.         0.         0.       ]
 [ 0.         0.         0.         0.         0.         0.       ]
 [-1.49058   -1.49058   -1.8190606 -1.49058   -1.49058   -9.       ]
 ...
 [ 0.         0.         0.         0.         0.         0.       ]
 [-0.9       -0.9        0.         0.         0.         0.       ]
 [ 0.         0.         0.         0.         0.         0.       ]]
